rov:
  maxHeartbeatGap: 5
  cpuPollInterval: 1
  sensorPollInterval: 10
  sleepDuration: 100
  maestroDeviceNumber: 0x01
  portAftChannel: 15
  starboardAftChannel: 12
  portForeChannel: 16
  starboardForeChannel: 13
  portVertChannel: 17
  starboardVertChannel: 14
  cameraAMotorChannel: 18
  cameraBMotorChannel: 19
  toolingMotorChannel: 22
  lightChannel: 23
  voltageSensor05VChannel: 8
  voltageSensor12VChannel: 7
  voltageSensor48VChannel: 6
  currentSensor05VChannel: 11
  currentSensor12VChannel: 10
  currentSensor48VChannel: 9
  altImuSa0High: false
  i2cBus: 1
