launch:
  broadcast: 192.168.88.255
  defaultBroadcastPort: 10003
  serialPort: /dev/ttyACM0
  baudRate: 115200
  heartbeatRate: 1
  fileReceiverPort: 12347
  fileReceiverSocketBacklog: 100
topsides:
  pilotPanelName: Pilot Panel
  pilotPanelPort: /dev/ttyACM0
  pilotPanelTimeOut: 2000
  pilotPanelBaud: 115200
  pilotPanelHeartbeatInterval: 500
  pilotPanelHeartbeatTimeout: 5000
  pilotPanelOutputs: [39,41,43,45,47,49,51,53,40,42,44,46,48,50,52]
  pilotPanelInputPullups: [25,27,29,31,33,35,37,22,24,26,28,30,32,34,36,38]
  joystickRecoveryInterval: 1000
  emergencyStopButtonAddress: 38
  preferencesHome: profiles
  motionPowerSwitchDuration: 2000
  motionPowerSaveFlashCount: 6
  motionPowerSaveFlashDuration: 200
  heartbeatLostInterval: 5
rov:
  maxHeartbeatGap: 5
  cpuPollInterval: 1
  sensorPollInterval: 100
  sleepDuration: 100
  maestroDeviceNumber: 0x01
  portAftChannel: 17
  starboardAftChannel: 2
  portForeChannel: 15
  starboardForeChannel: 1
  vertAftChannel: 0
  vertForeChannel: 16
  cameraAMotorChannel: 7
  cameraBMotorChannel: 10
  toolingAMotorChannel: 11
  toolingBMotorChannel: 5
  toolingCMotorChannel: 22
  lightAChannel: 23
  lightBChannel: 22
  altImuSa0High: false
  i2cBus: 1
  shutdownTimeout: 1000
  bluetoothComPortName: bluetooth
  bluetoothComPort: /dev/ttyS0
  bluetoothConnectionTimeout: 2000
  bluetoothBaudRate: 9600
  pressureSensorConvertTime: 20
videoDecoder:
  host: 192.168.88.2
  portA: 12345
  portB: 12346
  format: h264
  frameRate: 40
  socketBacklog: 100
  bitrate: 25000000
  preset: ultrafast
  numBuffers: 0
  introVideoLocation: /home/eedge/intro.h264
joystick:
  heaveAxis: slider
  swayAxis: x
  surgeAxis: y
  yawAxis: rz
  cameraAMotorForwardButton: Top|3
  cameraAMotorReverseButton: Pinkie|5
  cameraBMotorForwardButton: Top 2|4
  cameraBMotorReverseButton: Thumb 2|2
  toolingAMotorForwardButton: Base 5|10
  toolingAMotorReverseButton: Base 6|11
  toolingBMotorForwardButton: Base 5|10
  toolingBMotorReverseButton: Base 6|11
  toolingCMotorForwardButton: ""
  toolingCMotorReverseButton: ""
  motionReverseButton: Thumb|1
  cameraAVideoFlipButton: Base 2|7
  cameraBVideoFlipButton: Base|6
  pitchForwardButton: Base 4|9
  pitchReverseButton: Base 3|8
  cameraAMotorSpeed: 0.30f
  cameraBMotorSpeed: 0.30f
  toolingAMotorSpeed: 1f
  toolingBMotorSpeed: 1f
  toolingCMotorSpeed: 1f
  pitchSpeed: 1f
slider:
  globalPowerSliderAddress: 0
  heavePowerSliderAddress: 1
  swayPowerSliderAddress: 2
  surgePowerSliderAddress: 3
  pitchPowerSliderAddress: 4
  yawPowerSliderAddress: 5
  aftPowerSliderAddress: 6
  forePowerSliderAddress: 7
  lightAPowerSliderAddress: 8
  lightBPowerSliderAddress: 9
cameraCalibration:
  cameraAName: camera-a-1
  cameraBName: camera-b-1
  cameraAImagesDirectory: /home/eedge/calibration-a/
  cameraBImagesDirectory: /home/eedge/calibration-b/
  cameraAPreUndistortedDirectory: /home/eedge/pre-undistorted-a/
  cameraBPreUndistortedDirectory: /home/eedge/pre-undistorted-b/
  chessboardWidth: 6
  chessboardHeight: 9
distanceCalculator:
  imageDirectory: /home/eedge/undistorted-images/
  dataDirectory: /home/eedge/undistorted-images-data/
