launch:
  broadcast: 192.168.88.255
  defaultBroadcastPort: 10003
  serialPort: /dev/ttyACM0
  baudRate: 115200
topsides:
  pilotPanelName: Pilot Panel
  pilotPanelPort: /dev/ttyACM0
  pilotPanelTimeOut: 2000
  pilotPanelBaud: 115200
  pilotPanelHeartbeatInterval: 500
  pilotPanelHeartbeatTimeout: 5000
  pilotPanelOutputs: [22,24,26,28,30,32,34,36,38,53]
  pilotPanelInputPullups: [23,25,27,29,31,33,35,37,39]
  joystickRecoveryInterval: 1000
  emergencyStopButtonAddress: 53
  profileSwitchDuration: 2000
  profilePref: profiles
rov:
  maxHeartbeatGap: 5
  cpuPollInterval: 1
  sensorPollInterval: 10
  sleepDuration: 100
  maestroDeviceNumber: 0x01
  portAftChannel: 17
  starboardAftChannel: 2
  portForeChannel: 15
  starboardForeChannel: 1
  vertAftChannel: 0
  vertForeChannel: 16
  cameraAMotorChannel: 7
  cameraBMotorChannel: 10
  toolingMotorChannel: 5
  lightChannel: 23
  altImuSa0High: false
  i2cBus: 1
  shutdownTimeout: 1000
videoDecoder:
  host: 192.168.88.2
  portA: 12345
  portB: 12346
  format: h264
  frameRate: 48
  socketBacklog: 100
  bitrate: 25000000
  preset: ultrafast
  numBuffers: 0
joystick:
  heaveAxis: slider
  swayAxis: x
  surgeAxis: y
  yawAxis: rz
  cameraAMotorForwardButton: Top|3
  cameraAMotorReverseButton: Pinkie|5
  cameraBMotorForwardButton: Top 2|4
  cameraBMotorReverseButton: Thumb 2|2
  toolingMotorForwardButton: Base 5|10
  toolingMotorReverseButton: Base 6|11
  motionReverseButton: Thumb|1
  cameraAVideoFlipButton: Base 2|7
  cameraBVideoFlipButton: Base|6
  pitchForwardButton: Base 4|9
  pitchReverseButton: Base 3|8
  cameraAMotorSpeed: 0.30f
  cameraBMotorSpeed: 0.30f
  toolingMotorSpeed: 1f
  pitchSpeed: 1f
slider:
  globalPowerSliderAddress: 3
  heavePowerSliderAddress: 2
  swayPowerSliderAddress: 1
  surgePowerSliderAddress: 0
  pitchPowerSliderAddress: 4
  yawPowerSliderAddress: 5
  aftPowerSliderAddress: 6
  forePowerSliderAddress: 8
  lightPowerSliderAddress: 7
