- hosts: topside
  become: yes
  become_method: sudo
  vars:
    proxy:
      http_proxy: http://192.168.88.3:3128
      https_proxy: http://192.168.88.3:3128
  tasks:
    - set_fact:
          ssh_connection_ip: "{{ ansible_env['SSH_CONNECTION'].split()[2] }}"
    - set_fact:
          ssh_interface: "{{ item }}"
      when: "{{ hostvars[inventory_hostname]['ansible_' ~ item].get('ipv4', {}).get('address') == ssh_connection_ip }}"
      with_items: "{{ ansible_interfaces }}"
    - name: "Add eedge to input group (fixes #129)"
      user: name=eedge groups=input append=yes
    - name: Add MPV repo for Ubuntu 15.10
      apt_repository: repo='ppa:mc3man/ffmpeg-test1'
      environment: "{{proxy}}"
    - name: Install MPV
      apt: name=mpv state=latest
      environment: "{{proxy}}"
    - name: Install video drivers
      apt: name=mesa-vdpau-drivers state=latest
      environment: "{{proxy}}"
    - name: Install htop
      apt: name=htop state=latest
      environment: "{{proxy}}"
    - name: Install Java 8 Runtime
      apt: name=openjdk-8-jre state=latest
      tags: java
      environment: "{{proxy}}"
    - name: Install OpenJFX 8
      apt: name=openjfx state=latest
      tags: java
      environment: "{{proxy}}"
    - name: Install DHCP Server
      apt: name=isc-dhcp-server state=latest
      environment: "{{proxy}}"
    - name: Configure DHCP Service
      template: src=files/services/isc-dhcp-server dest=/etc/default/isc-dhcp-server mode=644 owner=root group=root
    - name: Configure DHCP Auto-restart
      template: src=files/etc/network/if-up.d/dhcp-server dest=/etc/network/if-up.d/dhcp-server mode=755 owner=root group=root
    - name: Configure DHCP Server
      copy: src=files/conf/dhcpd.conf dest=/etc/dhcp/dhcpd.conf mode=644 owner=root group=root
      notify: Restart DHCP Server
  handlers:
    - name: Restart DHCP Server
      service: name=isc-dhcp-server state=restarted
